name: keepalive
on:
  schedule:
    - cron: "0 * * * *"   # executa no minuto 0 de TODA hora (de hora em hora)
  workflow_dispatch:


jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase RPC
        run: |
          curl -sSf -X POST "$KEEPALIVE_URL" \
            -H "apikey: $SUPABASE_ANON_KEY" \
            -H "Authorization: Bearer $SUPABASE_ANON_KEY" \
            -H "Content-Type: application/json" \
            -d '{}' || exit 1
        env:
          KEEPALIVE_URL: ${{ secrets.KEEPALIVE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
